using System.Collections.Generic;
using UnityEngine;

public class Bullet : MonoBehaviour
{
    [SerializeField] private Collider m_attackCollider; //ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½ÌƒRï¿½ï¿½ï¿½Cï¿½_ï¿½[
    [SerializeField] private float m_speed; //ï¿½eï¿½ï¿½
    [SerializeField] private float m_destroyTime; //ï¿½ï¿½ï¿½Ë‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½íœï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Å‚Ìï¿½ï¿½ï¿½
    [SerializeField] private bool m_disappearOnHit; //ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½é‚©
    private List<CharaBase> m_hitList = new List<CharaBase>(); //ï¿½ï¿½xï¿½ÌUï¿½ï¿½ï¿½ï¿½ï¿½Å“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Gï¿½Ìƒï¿½ï¿½Xï¿½g(ï¿½ï¿½ï¿½iï¿½qï¿½bï¿½gï¿½Îï¿½)ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½Û‚ï¿½ï¿½Gï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ç‚¢ï¿½ï¿½È‚ï¿½
    [SerializeField] private float m_elapsedTime = 0f; //ï¿½oï¿½ßï¿½ï¿½ÔŒvï¿½ï¿½ï¿½pï¿½Ïï¿½
    private ObjectPool<Bullet> pool; //ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½vï¿½[ï¿½ï¿½
    private Rigidbody rb;

    ///<summary>
    ///ï¿½ï¿½ï¿½Ë‘Oï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Æ‚ß‚ï¿½ï¿½ï¿½ï¿½\ï¿½bï¿½h
    ///</summary>
    ///<param name="shooter">ï¿½ï¿½ï¿½ËŒï¿½(Playerï¿½ï¿½Enemy)</param>
    ///<param name="pool">ï¿½ï¿½ï¿½ï¿½ Bullet ï¿½Ìï¿½ï¿½ï¿½ï¿½vï¿½[ï¿½ï¿½</param>
    public void Initialize(GameObject shooter, ObjectPool<Bullet> pool)
    {
        //ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½É‰ï¿½ï¿½ï¿½ï¿½Äƒï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½İ’ï¿½
        if (shooter.CompareTag("Player"))
            gameObject.layer = LayerMask.NameToLayer("Player_Bullet");
        else if (shooter.CompareTag("Enemy"))
            gameObject.layer = LayerMask.NameToLayer("Enemy_Bullet");

        //ï¿½vï¿½[ï¿½ï¿½ï¿½oï¿½^
        this.pool = pool;

        //ï¿½ï¿½ï¿½Wï¿½bï¿½hï¿½{ï¿½fï¿½Bï¿½Ìİ’ï¿½ÏXï¿½Aï¿½Ç‚È‚Ç‚ï¿½ï¿½ï¿½ï¿½è”²ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½Éİ’ï¿½
        rb = GetComponent<Rigidbody>();
        rb.collisionDetectionMode = CollisionDetectionMode.Continuous;

        //ï¿½ï¿½ï¿½Wï¿½bï¿½hï¿½{ï¿½fï¿½Bï¿½Ì—Í‚Ìï¿½ï¿½ï¿½ï¿½ï¿½
        rb.linearVelocity = Vector3.zero;
        rb.angularVelocity = Vector3.zero;

        //ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½oï¿½ßï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½g
        m_hitList.Clear();
        m_elapsedTime = 0f;

        //ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ÍÅï¿½ï¿½Í–ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½AAttackStart()ï¿½Å—Lï¿½ï¿½ï¿½ï¿½
        m_attackCollider.enabled = false;

        //ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½ï¿½(ObjectPoolï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½inactiveï¿½È‚Ì‚ï¿½)
        gameObject.SetActive(true);
    }

    ///<summary>
    ///ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½
    ///</summary>
    private void Update()
    {
        //ï¿½fï¿½ï¿½ï¿½^ï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Z
        m_elapsedTime += Time.deltaTime;
        //ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ßï¿½ï¿½Ô‚ï¿½ï¿½íœï¿½ï¿½ï¿½Ô‚ï¿½ï¿½zï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½vï¿½[ï¿½ï¿½ï¿½É•Ô‹p
        if (m_elapsedTime > m_destroyTime)
        {
            pool.ReturnToPool(this);
        }
    }

    private void FixedUpdate()
    {
        //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
        rb.isKinematic = false;
        rb.AddForce(transform.forward * m_speed);
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½
    /// </summary>
    /// <param name="other">ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g</param>
    private void OnTriggerEnter(Collider other)
    {
        var chara = other.GetComponentInParent<CharaBase>();
        //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½ï¿½ÂAï¿½qï¿½bï¿½gï¿½ï¿½ï¿½Xï¿½gï¿½É–ï¿½ï¿½ï¿½ï¿½ï¿½ÎA
        //ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Éƒ_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½^ï¿½ï¿½ï¿½Aï¿½qï¿½bï¿½gï¿½ï¿½ï¿½Xï¿½gï¿½É’Ç‰ï¿½
        if (chara != null && !m_hitList.Contains(chara))
        {
            chara.GetDamage(1.0f);
            m_hitList.Add(chara);
            //ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½eï¿½È‚ï¿½Aï¿½vï¿½[ï¿½ï¿½ï¿½É•Ô‹p
            if (m_disappearOnHit)
            {
                pool.ReturnToPool(this);
            }
        }
    }

    ///<summary>
    ///ï¿½Uï¿½ï¿½ï¿½Jï¿½nï¿½Ìï¿½ï¿½ï¿½
    ///</summary>
    public void AttackStart()
    {
        //ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        m_hitList.Clear();
        //ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½
        m_attackCollider.enabled = true;
    }

    ///<summary>
    ///ï¿½Uï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    ///</summary>
    public void AttackEnd()
    {
        //ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ğ–³Œï¿½ï¿½ï¿½
        m_attackCollider.enabled = false;
    }
}
